In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib.ticker as ticker
import seaborn as sns

plt.rcParams["figure.figsize"] = (10,8)

import warnings
warnings.filterwarnings('ignore')

import pandas as pd

from sklearn.preprocessing import LabelEncoder  
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('/Users/davidfernandez/Desktop/diamonds/test.csv')

In [7]:
df_numericas = df.select_dtypes(include=np.number)

df_numericas

          id  carat  depth  table     x     y     z
0          0   0.32   60.5   58.0  4.43  4.49  2.70
1          1   1.24   62.9   60.0  6.80  6.74  4.26
2          2   1.66   62.0   59.0  7.55  7.60  4.70
3          3   0.75   60.6   56.0  5.94  5.90  3.59
4          4   1.50   64.8   55.0  7.26  7.15  4.67
...      ...    ...    ...    ...   ...   ...   ...
13480  13480   1.10   59.6   60.0  6.74  6.70  4.00
13481  13481   0.90   62.1   60.0  6.14  6.20  3.83
13482  13482   0.30   62.1   53.3  4.30  4.32  2.68
13483  13483   1.25   59.6   59.0  7.01  7.09  4.20
13484  13484   0.81   61.6   58.0  5.96  5.92  3.66

[13485 rows x 7 columns]

In [8]:
def detectar_outliers(lista_columnas, dataframe): 
    
    dicc_indices = {} # creamos un diccionario donde almacenaremos índices de los outliers
    
    # iteramos por la lista de las columnas numéricas de nuestro dataframe
    for col in lista_columnas:
        
        #calculamos los cuartiles Q1 y Q3
        Q1 = np.nanpercentile(dataframe[col], 25)
        Q3 = np.nanpercentile(dataframe[col], 75)
        
        # calculamos el rango intercuartil
        IQR = Q3 - Q1
        
        # calculamos los límites
        outlier_step = 1.5 * IQR
        
        # filtramos nuestro dataframe para indentificar los outliers
        outliers_data = dataframe[(dataframe[col] < Q1 - outlier_step) | (dataframe[col] > Q3 + outlier_step)]
        
        
        if outliers_data.shape[0] > 0: # chequeamos si nuestro dataframe tiene alguna fila. 
        
            dicc_indices[col] = (list(outliers_data.index)) # si tiene fila es que hay outliers y por lo tanto lo añadimos a nuestro diccionario
        

    
    return dicc_indices

In [10]:
lista_columnas = df_numericas.columns
lista_columnas

Index(['id', 'carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [12]:
ind = detectar_outliers(lista_columnas, df)
print(ind)

{'carat': [22, 27, 34, 39, 47, 112, 146, 194, 229, 239, 292, 307, 317, 354, 357, 360, 366, 384, 401, 403, 501, 511, 539, 608, 614, 705, 758, 763, 767, 769, 784, 796, 935, 976, 1025, 1033, 1046, 1128, 1150, 1237, 1267, 1285, 1353, 1373, 1385, 1398, 1439, 1481, 1507, 1549, 1569, 1573, 1588, 1591, 1684, 1689, 1708, 1753, 1778, 1795, 1796, 1804, 1844, 1851, 1900, 1905, 1907, 1954, 2051, 2063, 2077, 2115, 2160, 2288, 2297, 2341, 2354, 2366, 2396, 2461, 2463, 2465, 2474, 2567, 2615, 2642, 2656, 2662, 2755, 2901, 2913, 2915, 2932, 2955, 2970, 3088, 3112, 3122, 3141, 3170, 3219, 3236, 3251, 3275, 3297, 3353, 3362, 3425, 3428, 3443, 3454, 3458, 3555, 3564, 3565, 3631, 3658, 3677, 3767, 3834, 3920, 3935, 3985, 3989, 4007, 4014, 4084, 4120, 4156, 4188, 4189, 4229, 4232, 4259, 4285, 4313, 4345, 4369, 4476, 4496, 4525, 4526, 4531, 4542, 4594, 4610, 4612, 4640, 4656, 4669, 4678, 4689, 4740, 4747, 4800, 4810, 4897, 5011, 5076, 5102, 5135, 5179, 5216, 5249, 5302, 5327, 5361, 5433, 5454, 5458, 5519, 5585, 5588, 5602, 5648, 5661, 5678, 5696, 5748, 5789, 5792, 5817, 5838, 5863, 5871, 5885, 5896, 5902, 5920, 6001, 6007, 6051, 6085, 6165, 6186, 6205, 6313, 6398, 6424, 6467, 6474, 6504, 6519, 6524, 6539, 6606, 6619, 6632, 6633, 6634, 6655, 6678, 6718, 6736, 6823, 6830, 6895, 6946, 6983, 7027, 7042, 7069, 7095, 7200, 7255, 7299, 7325, 7348, 7366, 7376, 7392, 7419, 7563, 7564, 7620, 7636, 7671, 7678, 7682, 7706, 7807, 7818, 7830, 7844, 7858, 7862, 7897, 7924, 7925, 7971, 7977, 8019, 8049, 8060, 8079, 8127, 8165, 8236, 8284, 8303, 8343, 8357, 8368, 8410, 8418, 8543, 8613, 8628, 8634, 8644, 8652, 8664, 8669, 8675, 8720, 8741, 8755, 8759, 8760, 8772, 8781, 8782, 8801, 8850, 8922, 8957, 8999, 9008, 9010, 9034, 9039, 9051, 9067, 9098, 9185, 9189, 9210, 9232, 9265, 9268, 9280, 9364, 9405, 9424, 9430, 9436, 9447, 9461, 9464, 9491, 9495, 9570, 9601, 9612, 9644, 9646, 9819, 9904, 9988, 9991, 10020, 10125, 10150, 10151, 10181, 10276, 10298, 10305, 10433, 10448, 10460, 10491, 10507, 10521, 10540, 10569, 10572, 10595, 10637, 10750, 10767, 10774, 10789, 10817, 10896, 10906, 10937, 10988, 11042, 11051, 11146, 11170, 11211, 11261, 11279, 11307, 11371, 11374, 11387, 11432, 11461, 11493, 11504, 11576, 11601, 11620, 11624, 11644, 11654, 11675, 11724, 11734, 11739, 11784, 11793, 11806, 11838, 11859, 11874, 11921, 11932, 11949, 11957, 11962, 11971, 12028, 12034, 12059, 12081, 12110, 12117, 12120, 12148, 12157, 12185, 12274, 12312, 12317, 12347, 12393, 12395, 12409, 12415, 12433, 12451, 12463, 12483, 12519, 12554, 12605, 12681, 12686, 12727, 12733, 12754, 12858, 12873, 12916, 12931, 12982, 12998, 13034, 13045, 13090, 13108, 13209, 13220, 13236, 13251, 13265, 13309, 13311, 13353, 13379, 13418, 13419, 13430, 13456, 13467], 'depth': [4, 23, 35, 40, 67, 87, 140, 154, 160, 161, 179, 191, 231, 326, 342, 360, 365, 368, 382, 384, 449, 450, 467, 486, 502, 510, 561, 579, 582, 601, 666, 667, 684, 685, 710, 715, 738, 743, 752, 769, 772, 775, 783, 793, 795, 839, 843, 885, 891, 897, 898, 923, 932, 940, 994, 997, 1007, 1015, 1046, 1050, 1099, 1102, 1108, 1131, 1150, 1169, 1202, 1204, 1229, 1237, 1241, 1262, 1282, 1298, 1365, 1407, 1424, 1427, 1434, 1472, 1479, 1484, 1487, 1500, 1518, 1519, 1521, 1529, 1537, 1541, 1547, 1550, 1595, 1621, 1627, 1650, 1655, 1676, 1677, 1683, 1691, 1707, 1733, 1734, 1737, 1767, 1782, 1795, 1800, 1805, 1815, 1817, 1823, 1844, 1845, 1861, 1890, 1906, 1907, 1990, 1997, 2052, 2053, 2063, 2084, 2089, 2093, 2099, 2109, 2114, 2117, 2124, 2148, 2193, 2224, 2234, 2262, 2267, 2278, 2279, 2280, 2281, 2284, 2319, 2329, 2350, 2396, 2401, 2403, 2434, 2443, 2448, 2450, 2479, 2494, 2504, 2507, 2549, 2577, 2578, 2645, 2666, 2716, 2766, 2767, 2805, 2822, 2834, 2837, 2846, 2865, 2878, 2890, 2903, 2912, 2915, 2937, 2942, 2973, 2993, 3079, 3110, 3112, 3115, 3142, 3153, 3159, 3162, 3226, 3247, 3257, 3277, 3279, 3289, 3296, 3308, 3310, 3312, 3328, 3344, 3347, 3351, 3362, 3440, 3452, 3454, 3473, 3511, 3523, 3541, 3565, 3569, 3617, 3623, 3643, 3681, 3683, 3713, 3735, 3790, 3800, 3804, 3823, 3857, 3864, 3895, 3897, 3916, 3928, 3937, 3940, 3942, 3959, 4004, 4007, 4044, 4061, 4064, 4089, 4101, 4150, 4153, 4156, 4169, 4186, 4193, 4211, 4243, 4253, 4259, 4264, 4289, 4321, 4328, 4349, 4368, 4384, 4399, 4406, 4475, 4476, 4504, 4530, 4533, 4569, 4574, 4576, 4592, 4609, 4614, 4640, 4680, 4700, 4701, 4702, 4732, 4743, 4757, 4762, 4789, 4800, 4812, 4819, 4829, 4831, 4841, 4876, 4878, 4911, 5028, 5031, 5039, 5065, 5108, 5112, 5126, 5133, 5150, 5183, 5234, 5247, 5261, 5310, 5312, 5357, 5387, 5389, 5391, 5392, 5410, 5423, 5454, 5459, 5468, 5469, 5488, 5495, 5521, 5575, 5581, 5602, 5608, 5643, 5688, 5696, 5700, 5732, 5739, 5742, 5771, 5796, 5827, 5845, 5862, 5870, 5885, 5891, 5912, 5925, 5928, 5959, 5986, 6004, 6023, 6033, 6036, 6044, 6051, 6053, 6058, 6075, 6082, 6090, 6091, 6096, 6142, 6163, 6179, 6199, 6208, 6224, 6275, 6297, 6299, 6337, 6340, 6345, 6347, 6348, 6361, 6408, 6439, 6447, 6450, 6457, 6459, 6465, 6503, 6506, 6532, 6577, 6589, 6619, 6629, 6646, 6669, 6674, 6684, 6712, 6760, 6782, 6835, 6840, 6841, 6864, 6869, 6870, 6883, 6897, 6961, 7001, 7065, 7090, 7094, 7120, 7139, 7153, 7156, 7159, 7162, 7166, 7210, 7223, 7228, 7229, 7234, 7247, 7261, 7271, 7276, 7298, 7306, 7336, 7345, 7377, 7445, 7455, 7458, 7464, 7472, 7474, 7500, 7502, 7506, 7538, 7552, 7555, 7567, 7587, 7597, 7601, 7639, 7657, 7663, 7670, 7671, 7674, 7710, 7713, 7716, 7728, 7731, 7765, 7785, 7834, 7837, 7839, 7844, 7874, 7882, 7900, 7935, 7942, 7945, 7972, 7984, 7989, 8002, 8058, 8071, 8074, 8079, 8098, 8099, 8103, 8106, 8184, 8186, 8207, 8222, 8245, 8259, 8267, 8297, 8303, 8322, 8336, 8350, 8375, 8378, 8379, 8391, 8405, 8448, 8490, 8494, 8505, 8513, 8557, 8562, 8568, 8578, 8587, 8620, 8650, 8683, 8695, 8697, 8712, 8745, 8786, 8801, 8820, 8831, 8837, 8855, 8916, 8923, 8938, 8940, 8965, 8968, 8999, 9010, 9049, 9052, 9114, 9128, 9152, 9177, 9204, 9206, 9218, 9226, 9247, 9258, 9296, 9299, 9346, 9416, 9430, 9435, 9437, 9441, 9444, 9451, 9469, 9521, 9522, 9523, 9549, 9591, 9596, 9599, 9617, 9634, 9638, 9717, 9750, 9753, 9778, 9793, 9800, 9808, 9823, 9838, 9839, 9863, 9874, 9881, 9928, 9950, 10014, 10097, 10113, 10123, 10128, 10175, 10190, 10202, 10257, 10266, 10271, 10279, 10297, 10311, 10366, 10379, 10403, 10432, 10479, 10480, 10500, 10517, 10558, 10576, 10579, 10596, 10612, 10623, 10631, 10659, 10693, 10711, 10717, 10748, 10802, 10821, 10830, 10832, 10849, 10867, 10882, 10900, 10903, 10910, 10925, 10970, 10984, 11037, 11039, 11048, 11051, 11061, 11081, 11116, 11154, 11195, 11242, 11296, 11344, 11366, 11383, 11389, 11422, 11532, 11544, 11551, 11565, 11618, 11625, 11658, 11664, 11710, 11727, 11795, 11800, 11819, 11825, 11874, 11886, 11937, 11958, 11967, 11983, 11999, 12009, 12028, 12058, 12089, 12111, 12155, 12201, 12203, 12224, 12235, 12242, 12244, 12263, 12295, 12302, 12307, 12347, 12349, 12355, 12381, 12397, 12405, 12421, 12433, 12442, 12444, 12476, 12515, 12567, 12598, 12620, 12625, 12666, 12674, 12676, 12778, 12785, 12802, 12833, 12872, 12873, 12911, 12918, 12926, 12941, 12946, 12949, 12953, 12965, 12968, 12971, 12972, 12975, 12982, 13008, 13045, 13058, 13059, 13084, 13108, 13128, 13154, 13173, 13197, 13218, 13237, 13238, 13255, 13259, 13266, 13267, 13307, 13314, 13317, 13331, 13367, 13378, 13381, 13383, 13393, 13400, 13438, 13472, 13479], 'table': [29, 182, 218, 257, 317, 413, 433, 474, 483, 509, 553, 557, 775, 928, 1050, 1057, 1085, 1108, 1131, 1289, 1402, 1407, 1497, 1542, 1627, 1670, 1691, 1815, 1817, 1845, 1981, 2057, 2076, 2099, 2192, 2299, 2322, 2496, 2825, 2901, 3095, 3205, 3363, 3425, 3580, 3683, 3694, 3814, 3816, 3823, 3880, 3959, 4044, 4079, 4133, 4159, 4168, 4368, 4382, 4454, 4476, 4569, 4834, 4943, 5031, 5065, 5281, 5370, 5507, 5598, 5723, 5725, 5940, 6236, 6299, 6379, 6407, 6437, 6532, 6712, 6858, 6883, 7210, 7247, 7377, 7458, 7506, 7602, 7713, 7758, 7782, 7935, 8099, 8245, 8267, 8378, 8401, 8431, 8568, 8609, 8667, 8780, 8786, 8900, 8915, 8967, 8968, 9052, 9242, 9328, 9591, 9668, 9728, 9844, 9874, 9929, 10037, 10080, 10148, 10234, 10238, 10315, 10410, 10432, 10464, 10545, 10623, 10641, 10793, 10822, 10906, 10970, 11039, 11098, 11355, 11389, 11422, 11478, 11504, 11600, 11601, 11625, 11716, 12002, 12236, 12242, 12336, 12421, 12567, 12654, 12687, 13059, 13064, 13155, 13161, 13331, 13441], 'x': [2396, 2755, 4120, 6633, 8079, 8786, 13456], 'y': [2396, 2755, 4120, 6633, 8079, 8786, 13456], 'z': [4120, 8079, 8786, 8876, 10219, 13251, 13456]}

In [14]:
# lo que vamos a hacer es iterar por el diccionario que nos devuelve la función 
for k, v in ind.items():
        media = df[k].mean() # calculamos la media para cada una de las columnas que tenemos en nuestro diccionario
        for i in v: # iteremos por la lista de valores para cada columna
            df.loc[i,k] = media # usando el loc, reemmplazamos los valores de los outliers por la media que hemos calculado al inicio.

In [15]:
df_categoricas = df.select_dtypes(include=['object'])

df_categoricas # These are the columns to which we're going to apply the 'get dummies' encoding

             cut color clarity
0          Ideal     I     SI1
1        Premium     I     SI1
2        Premium     D     SI1
3        Premium     D     SI2
4           Fair     E     SI2
...          ...   ...     ...
13480    Premium     G     SI1
13481  Very Good     D     SI1
13482      Ideal     F     VS2
13483      Ideal     I     SI1
13484    Premium     F     SI1

[13485 rows x 3 columns]

In [16]:
# 'Cut' column:

dummies_cut = pd.get_dummies(df["cut"], prefix_sep = "_", prefix = "cut", dtype = int)

df[dummies_cut.columns] = dummies_cut
df.drop(["cut"], axis = 1, inplace = True)

In [17]:
# 'color' column

dummies_color = pd.get_dummies(df["color"], prefix_sep = "_", prefix = "color", dtype = int)

df[dummies_color.columns] = dummies_color
df.drop(["color"], axis = 1, inplace = True)

In [18]:
# 'clarity' column

dummies_clarity = pd.get_dummies(df["clarity"], prefix_sep = "_", prefix = "clarity", dtype = int)

df[dummies_clarity.columns] = dummies_clarity
df.drop(["clarity"], axis = 1, inplace = True)

In [20]:
df.to_csv('reality2.csv')